In [2]:
import pandas as pd
import os

os.chdir(r"C:\Users\steph\Downloads\lab1\e_comm_project")

Read both csv files

In [3]:
df1 = pd.read_csv(r"C:\Users\steph\Downloads\archive (4)\customers.csv")

Data cleaning first csv "customers.csv"

In [4]:
df1.head()

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
0,CUST0001,Gandi,26.0,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
1,CUST0002,Cecep,49.0,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No
2,CUST0003,Artawan,26.0,Male,Jambi,2025-02-11,wahyuninovi@example.net,8692932468,Yes
3,CUST0004,Mulya,61.0,Male,Nusa Tenggara Timur,2025-02-19,nnapitupulu@example.com,8515735210,Yes
4,CUST0005,Taufik,43.0,Male,Kepulauan Riau,2025-08-04,taufik_87@example.com,81034538051,Yes

10 column dupes

In [5]:
df1["customer_id"].duplicated().sum()

np.int64(10)

Spelling Check

In [6]:
df1["state"].value_counts().sort_index()

state
Aceh                         34
Bali                         26
Banten                       37
Bengkulu                     24
DI Yogyakarta                27
DKI Jakarta                  28
Gorontalo                    28
Jambi                        24
Jawa Barat                   25
Jawa Tengah                  28
Jawa Timur                   35
Kalimantan Barat             25
Kalimantan Selatan           19
Kalimantan Tengah            28
Kalimantan Timur             31
Kalimantan Utara             25
Kepulauan Bangka Belitung    34
Kepulauan Riau               33
Lampung                      30
Maluku                       23
Maluku Utara                 27
Nusa Tenggara Barat          32
Nusa Tenggara Timur          23
Papua                        36
Papua Barat                  31
Riau                         31
Sulawesi Barat               18
Sulawesi Selatan             23
Sulawesi Tengah              17
Sulawesi Tenggara            31
Sulawesi Utara               33
Sumatera Barat               32
Sumatera Selatan             25
Sumatera Utara               33
Name: count, dtype: int64

Check all duplicated rows and original rows as there's 10

In [7]:
df1[df1.duplicated(keep= False)]

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
20,CUST0514,Adinata,60.0,Male,Aceh,2023-12-11,bgunawan@example.net,8287301073,Yes
72,CUST0679,Jayadi,46.0,Male,Kepulauan Bangka Belitung,2025-09-20,998jayadi@example.com,84642406422,No
104,CUST0522,Lurhur,34.0,Male,Papua,2024-08-14,andrianidimas@example.org,8739118659,Yes
108,CUST0412,Tira,65.0,Female,Riau,2024-12-22,tira_61@example.com,840843370,No
121,CUST0137,Faizah,58.0,Female,Sulawesi Tenggara,2025-02-15,faizah137@example.com,824030244596,Yes
141,CUST0137,Faizah,58.0,Female,Sulawesi Tenggara,2025-02-15,faizah137@example.com,824030244596,Yes
274,CUST0661,Puji,32.0,Female,DI Yogyakarta,2025-09-05,puji_62@example.com,82263520270,Yes
417,CUST0412,Tira,65.0,Female,Riau,2024-12-22,tira_61@example.com,840843370,No
440,CUST0738,Tugiman,25.0,Male,Banten,2025-02-08,tugiman_3@example.com,8928576444,Yes
520,CUST0514,Adinata,60.0,Male,Aceh,2023-12-11,bgunawan@example.net,8287301073,Yes
528,CUST0522,Lurhur,34.0,Male,Papua,2024-08-14,andrianidimas@example.org,8739118659,Yes
615,CUST0860,Winda,38.0,Female,NaN,2025-08-09,549winda@example.com,873339264,Yes
634,CUST0627,Jelita,22.0,Female,Riau,2023-11-30,jelita_54@example.com,8407248064,Yes
668,CUST0661,Puji,32.0,Female,DI Yogyakarta,2025-09-05,puji_62@example.com,82263520270,Yes
686,CUST0679,Jayadi,46.0,Male,Kepulauan Bangka Belitung,2025-09-20,998jayadi@example.com,84642406422,No
703,CUST0627,Jelita,22.0,Female,Riau,2023-11-30,jelita_54@example.com,8407248064,Yes
746,CUST0738,Tugiman,25.0,Male,Banten,2025-02-08,tugiman_3@example.com,8928576444,Yes
749,CUST0741,Julia,55.0,Female,Jawa Barat,2024-11-07,dharyanto@example.com,83962790748,Yes
867,CUST0741,Julia,55.0,Female,Jawa Barat,2024-11-07,dharyanto@example.com,83962790748,Yes
869,CUST0860,Winda,38.0,Female,NaN,2025-08-09,549winda@example.com,873339264,Yes

Remove dupes and confirmed they're removed

In [8]:
df1 = df1.drop_duplicates()

In [9]:
df1.duplicated().sum()

np.int64(0)

In [10]:
df1[df1.duplicated(keep= False)]

Empty DataFrame
Columns: [customer_id, name, age, gender, state, signup_date, email, phone_number, subscribe]
Index: []

Check for missing values

In [11]:
df1[df1["age"].isnull()]

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
19,CUST0020,Ajimin,NaN,Male,Bengkulu,2024-10-09,ajimin354@example.com,857252618973,Yes
59,CUST0059,Eko,NaN,Male,Sulawesi Selatan,2025-07-07,teddy33@example.net,82140921512,Yes
97,CUST0096,Kamila,NaN,Female,Nusa Tenggara Barat,2024-08-09,kamila440@example.com,8886490325,No
132,CUST0128,Restu,NaN,Female,Sulawesi Selatan,2023-12-19,uwaisjail@example.net,84987516839,Yes
140,CUST0136,Anggabaya,NaN,Male,Gorontalo,2025-03-21,ekopuspasari@example.net,814729402780,Yes
227,CUST0223,Artanto,NaN,Male,Aceh,2023-11-12,gunartomaida@example.org,8579114663,Yes
240,CUST0236,Leo,NaN,Male,Sumatera Selatan,2025-08-19,jagaragasaputra@example.net,816809421,Yes
255,CUST0251,Prima,NaN,Male,Sulawesi Selatan,2024-09-02,putu16@example.net,869004782947,No
258,CUST0254,Uchita,NaN,Female,Kalimantan Utara,2024-10-21,kartika75@example.net,868108247332,Yes
268,CUST0264,Sarah,NaN,Female,DKI Jakarta,2025-01-12,sarah_50@example.com,859373944,Yes
301,CUST0296,Pangeran,NaN,Male,Aceh,2024-06-11,aminashiruddin@example.net,83882910039,Yes
329,CUST0324,Tania,NaN,Female,Papua Barat,2024-11-19,kayunmansur@example.org,826931207,Yes
334,CUST0329,Lili,NaN,Female,Bengkulu,2023-11-29,edi88@example.com,829276468,No
358,CUST0353,Bella,NaN,Female,Bengkulu,2025-07-10,xrahmawati@example.org,86663721052,Yes
397,CUST0392,Garang,NaN,Male,Sumatera Selatan,2025-05-31,jmaryati@example.com,878467427,Yes
430,CUST0425,Eluh,NaN,Male,DI Yogyakarta,2023-12-25,jpalastri@example.com,8586798739,Yes
433,CUST0428,Himawan,NaN,Male,Maluku Utara,2024-03-15,cprakasa@example.com,81296339629,Yes
434,CUST0429,Hendri,NaN,Male,DI Yogyakarta,2024-08-15,margana84@example.net,8303439050,Yes
479,CUST0473,Tasnim,NaN,Male,Banten,2024-06-23,tasnim_1@example.com,8906479961,Yes
497,CUST0491,Okto,NaN,Male,Sulawesi Selatan,2024-05-21,miswahyudi@example.org,822430125835,Yes
529,CUST0523,Satya,NaN,Male,Kepulauan Riau,2025-09-03,185satya@example.com,864794405,Yes
541,CUST0535,Padmi,NaN,Female,Kepulauan Bangka Belitung,2024-05-16,551padmi@example.com,835329272,Yes
573,CUST0567,Cagak,NaN,Male,Nusa Tenggara Barat,2023-09-28,gantar77@example.com,881592087,Yes
575,CUST0569,Padmi,NaN,Female,Kalimantan Barat,2025-05-04,padmi889@example.com,8574252962,Yes
586,CUST0580,Lala,NaN,Female,DKI Jakarta,2024-04-05,jmayasari@example.org,809443000765,No
600,CUST0594,Gina,NaN,Female,Gorontalo,2023-12-25,shanialailasari@example.net,818590978872,No
618,CUST0611,Gilda,NaN,Female,Maluku Utara,2025-05-02,620gilda@example.com,813990681066,Yes
622,CUST0615,Aurora,NaN,Female,Bali,2024-02-20,439aurora@example.com,808862476,Yes
643,CUST0636,Mustika,NaN,Male,Sulawesi Tenggara,2024-03-28,bala07@example.com,8806412674,Yes
656,CUST0649,Caturangga,NaN,Male,Nusa Tenggara Timur,2024-02-15,padmasariganjaran@example.net,842940543,Yes
670,CUST0663,Melinda,NaN,Female,Jawa Timur,2025-01-12,989melinda@example.com,8605603918,Yes
692,CUST0685,Jaiman,NaN,Male,Sulawesi Selatan,2024-08-11,jaiman538@example.com,818103569,Yes
693,CUST0686,Slamet,NaN,Male,Gorontalo,2024-02-28,144slamet@example.com,825675276374,Yes
714,CUST0706,Carla,NaN,Female,Lampung,2024-04-11,carla92@example.com,88670205486,Yes
732,CUST0724,Ayu,NaN,Female,Sulawesi Selatan,2025-03-05,pastuti@example.net,842274101,Yes
741,CUST0733,Michelle,NaN,Female,DI Yogyakarta,2024-04-01,budimanparman@example.org,874704018,No
750,CUST0742,Cengkal,NaN,Male,Jawa Tengah,2025-02-05,dodowibisono@example.org,844962659438,Yes
751,CUST0743,Aisyah,NaN,Female,Sumatera Utara,2024-11-07,aisyah_93@example.com,858705112293,No
755,CUST0747,Nilam,NaN,Female,Maluku Utara,2025-04-16,citraprabowo@example.org,86848771857,Yes
770,CUST0762,Jayeng,NaN,Male,Sulawesi Tenggara,2024-05-06,jayeng_70@example.com,81210847202,No
780,CUST0772,Tania,NaN,Female,Nusa Tenggara Timur,2024-05-03,tania413@example.com,859532978460,No
786,CUST0778,Embuh,NaN,Male,Papua,2024-06-02,among30@example.net,8135942920,Yes
826,CUST0818,Sabar,NaN,Male,Papua Barat,2024-12-12,melindanarpati@example.org,81276584519,Yes
858,CUST0850,Prayitna,NaN,Male,NaN,2024-12-18,narjisaputra@example.org,844800866,No
896,CUST0887,Virman,NaN,Male,NaN,2025-08-29,shaniamustofa@example.com,83833992395,Yes
897,CUST0888,Gandewa,NaN,Male,Sulawesi Tengah,2024-04-08,gandewa469@example.com,87050617081,Yes
900,CUST0891,Ajiono,NaN,Male,Sulawesi Tenggara,2024-11-27,wahyunicemplunk@example.net,836503634174,No
922,CUST0913,Nilam,NaN,Female,Jawa Timur,2025-02-19,pranowoellis@example.org,844021480822,No
926,CUST0917,Uli,NaN,Female,Kepulauan Bangka Belitung,2024-09-28,uli_32@example.com,809566847541,Yes
947,CUST0938,Dipa,NaN,Male,NaN,2024-10-01,7dipa@example.com,818949963,No
958,CUST0949,Ifa,NaN,Female,NaN,2025-02-10,irmajanuar@example.net,840186423,Yes
961,CUST0952,Hamima,NaN,Female,Sumatera Barat,2025-03-18,hamima_31@example.com,827321819680,Yes
973,CUST0964,Yance,NaN,Female,Papua Barat,2023-10-02,yance_14@example.com,8056592022,Yes
985,CUST0976,Vino,NaN,Male,Kepulauan Riau,2025-09-13,189vino@example.com,898203519355,Yes
986,CUST0977,Ani,NaN,Female,Kepulauan Bangka Belitung,2023-11-08,ani_59@example.com,828902780,Yes
998,CUST0989,Kala,NaN,Male,Riau,2025-03-01,opangestu@example.com,817697286,Yes

In [12]:
df1[df1["state"].isnull()]

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
38,CUST0038,Ganep,27.0,Male,NaN,2024-04-02,uwaishimawan@example.org,800743640,Yes
71,CUST0071,Faizah,60.0,Female,NaN,2024-12-09,hwidiastuti@example.com,898502533,Yes
77,CUST0076,Novi,41.0,Female,NaN,2024-06-21,eka06@example.com,825670214,Yes
85,CUST0084,Cemeti,43.0,Male,NaN,2024-06-10,cemani42@example.org,82769374044,Yes
86,CUST0085,Diana,23.0,Female,NaN,2025-01-23,diana214@example.com,8261158450,Yes
92,CUST0091,Gadang,48.0,Male,NaN,2024-01-02,gadang_44@example.com,83406335553,No
94,CUST0093,Syahrini,34.0,Female,NaN,2024-07-14,hariputra@example.com,87412241378,Yes
118,CUST0115,Febi,60.0,Female,NaN,2023-12-18,853febi@example.com,834936269296,Yes
134,CUST0130,Paulin,21.0,Female,NaN,2024-10-22,osimanjuntak@example.com,87062587103,Yes
142,CUST0138,Wulan,45.0,Female,NaN,2025-07-16,wulan_37@example.com,81397393326,No
146,CUST0142,Ami,42.0,Female,NaN,2023-12-12,ytamba@example.net,84571050970,Yes
177,CUST0173,Edi,46.0,Male,NaN,2024-04-15,balijan55@example.org,812844433,Yes
179,CUST0175,Dartono,52.0,Male,NaN,2025-02-15,harsanto83@example.com,889953743153,Yes
203,CUST0199,Daliono,45.0,Male,NaN,2024-08-18,widiastutiyulia@example.net,89234334959,Yes
217,CUST0213,Cornelia,38.0,Female,NaN,2025-01-31,setiawanpadmi@example.org,82199034845,Yes
236,CUST0232,Jamil,60.0,Male,NaN,2024-12-21,harihutapea@example.net,826116797,Yes
247,CUST0243,Calista,51.0,Female,NaN,2025-04-01,calista602@example.com,871806674460,No
266,CUST0262,Luis,44.0,Male,NaN,2024-11-21,tasnimhalimah@example.net,818973258242,Yes
270,CUST0266,Bahuraksa,23.0,Male,NaN,2024-05-22,kacungkuswoyo@example.net,84553407556,No
294,CUST0289,Anita,21.0,Female,NaN,2024-06-30,ayusalahudin@example.net,839364471,No
323,CUST0318,Tina,40.0,Female,NaN,2024-02-05,ykuswandari@example.org,84458373349,No
353,CUST0348,Ellis,39.0,Female,NaN,2025-04-21,nainggolanasirwanda@example.org,818027703691,No
365,CUST0360,Manah,52.0,Male,NaN,2025-05-19,irfan84@example.net,85538675090,Yes
375,CUST0370,Kiandra,55.0,Female,NaN,2025-02-07,572kiandra@example.com,8772086268,No
413,CUST0408,Tania,33.0,Female,NaN,2023-12-19,tania_31@example.com,853252996437,No
441,CUST0435,Wakiman,48.0,Male,NaN,2025-08-27,wakiman_43@example.com,83570133405,Yes
456,CUST0450,Taufik,29.0,Male,NaN,2025-05-18,hanayuniar@example.org,808810614,Yes
458,CUST0452,Kadir,43.0,Male,NaN,2024-12-31,kadir_23@example.com,877702556434,No
468,CUST0462,Anita,47.0,Female,NaN,2025-06-23,anita_19@example.com,818292192,No
511,CUST0505,Farhunnisa,43.0,Female,NaN,2024-11-30,melaniputu@example.org,83122555896,Yes
547,CUST0541,Nadine,40.0,Female,NaN,2025-04-02,910nadine@example.com,89144806208,Yes
551,CUST0545,Cahyanto,33.0,Male,NaN,2024-03-14,damanikhari@example.com,8229338944,Yes
607,CUST0601,Asirwanda,21.0,Male,NaN,2024-03-04,asirwanda_21@example.com,8431403682,Yes
615,CUST0860,Winda,38.0,Female,NaN,2025-08-09,549winda@example.com,873339264,Yes
641,CUST0634,Cemeti,34.0,Male,NaN,2024-04-04,cemplunkwidodo@example.com,852504513,Yes
648,CUST0641,Jagaraga,60.0,Male,NaN,2023-10-07,107jagaraga@example.com,8990445119,Yes
657,CUST0650,Edi,33.0,Male,NaN,2023-11-10,66edi@example.com,823265292645,Yes
690,CUST0683,Aisyah,21.0,Female,NaN,2025-02-11,agusadriansyah@example.net,86445039754,Yes
716,CUST0708,Safina,47.0,Female,NaN,2024-02-04,bambang52@example.net,839301635,Yes
756,CUST0748,Tantri,50.0,Female,NaN,2024-08-18,tantri_19@example.com,8862206790,Yes
767,CUST0759,Zelda,60.0,Female,NaN,2025-07-14,ndongoran@example.org,866263295,Yes
783,CUST0775,Tedi,57.0,Male,NaN,2024-04-27,hartatiwasis@example.net,8833792563,Yes
792,CUST0784,Indah,44.0,Female,NaN,2024-03-23,tantrirajata@example.net,869219285856,No
797,CUST0789,Zahra,39.0,Female,NaN,2024-10-30,agustinaenteng@example.com,8611018654,No
850,CUST0842,Gabriella,30.0,Female,NaN,2024-08-08,rezasihotang@example.net,879151819,No
858,CUST0850,Prayitna,NaN,Male,NaN,2024-12-18,narjisaputra@example.org,844800866,No
871,CUST0862,Gawati,18.0,Female,NaN,2024-01-16,gawati_15@example.com,813401534509,No
896,CUST0887,Virman,NaN,Male,NaN,2025-08-29,shaniamustofa@example.com,83833992395,Yes
945,CUST0936,Jaiman,62.0,Male,NaN,2024-05-06,napitupuludarsirah@example.com,8982461298,Yes
947,CUST0938,Dipa,NaN,Male,NaN,2024-10-01,7dipa@example.com,818949963,No
958,CUST0949,Ifa,NaN,Female,NaN,2025-02-10,irmajanuar@example.net,840186423,Yes
977,CUST0968,Irma,36.0,Female,NaN,2024-03-19,irma242@example.com,836733261166,Yes
993,CUST0984,Empluk,29.0,Male,NaN,2024-06-29,empluk_60@example.com,869492341,No

Check and fix data types

In [13]:
df1.dtypes

customer_id         str
name                str
age             float64
gender              str
state               str
signup_date         str
email               str
phone_number      int64
subscribe           str
dtype: object

In [14]:
df1["signup_date"] = pd.to_datetime(df1["signup_date"])

In [15]:
df1["phone_number"] = df1["phone_number"].astype("string")

In [16]:
df1["age"] = df1["age"].astype("Int64")

In [17]:
df1.dtypes

customer_id                str
name                       str
age                      Int64
gender                     str
state                      str
signup_date     datetime64[us]
email                      str
phone_number            string
subscribe                  str
dtype: object

In [18]:
df1.head()

,customer_id,name,age,gender,state,signup_date,email,phone_number,subscribe
0,CUST0001,Gandi,26,Male,Sulawesi Utara,2025-05-05,gandi_96@example.com,8422757160,No
1,CUST0002,Cecep,49,Male,Aceh,2025-06-02,cecep467@example.com,88171122035,No
2,CUST0003,Artawan,26,Male,Jambi,2025-02-11,wahyuninovi@example.net,8692932468,Yes
3,CUST0004,Mulya,61,Male,Nusa Tenggara Timur,2025-02-19,nnapitupulu@example.com,8515735210,Yes
4,CUST0005,Taufik,43,Male,Kepulauan Riau,2025-08-04,taufik_87@example.com,81034538051,Yes

In [19]:
df1.shape

(1000, 9)

Gender and null check

In [20]:
age_missing_percent = df1["age"].isna().mean() * 100
print("%",age_missing_percent)

% 5.6000000000000005

State Null Check

In [22]:
state_missing_percent = df1["state"].isna().mean() * 100
print("%",state_missing_percent)

% 5.3

In [21]:
df1.to_csv("customers_cleaned.csv", index=False)